nome = str(input('Digite seu nome:')).split()
v = len(nome)
print('Prazer em te conhecer {} {}'.format(nome[0], nome[1]))
print('Seu primeiro nome é: {}'.format(nome[0]))
print('Seu último nome é: {}'.format(nome[len(nome)-1]))
